import { test } from 'bun:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {
  generatePiExtension,
  getPiIntegrationStatus,
  installPiIntegration,
  piExtensionPath,
  runIntegrationsInstall,
  runIntegrationsStatus,
  WATCHER_MARKER,
} from '../src/integrationsInstaller.js';

async function tempHome(): Promise<string> {
  return fs.mkdtemp(path.join(os.tmpdir(), 'watcher-integrations-'));
}

test('watcher integrations install pi writes managed Pi extension and reload guidance', async () => {
  const home = await tempHome();
  const result = await runIntegrationsInstall(['pi'], { home });
  const target = piExtensionPath(home);
  const content = await fs.readFile(target, 'utf8');
  assert.equal(result.code, 0);
  assert.match(result.output, /Installed Pi Agent Event Source/);
  assert.match(result.output, /\/reload/);
  assert.match(content, new RegExp(WATCHER_MARKER));
  assert.match(content, /Generated by watcher integrations install pi/);
  assert.match(content, /pi\.on\("session_start"/);
  assert.match(content, /report\("session-started"/);
  assert.match(content, /pi\.on\("before_agent_start"/);
  assert.match(content, /report\("user-message", \{ text: event\.prompt/);
  assert.match(content, /pi\.on\("message_end"/);
  assert.match(content, /report\("assistant-message", \{ text/);
  assert.match(content, /pi\.on\("tool_execution_start"/);
  assert.match(content, /report\("tool-started"/);
  assert.match(content, /pi\.on\("tool_execution_update"/);
  assert.match(content, /report\("tool-updated"/);
  assert.match(content, /pi\.on\("tool_execution_end"/);
  assert.match(content, /report\("tool-finished"/);
  assert.match(content, /pi\.on\("agent_end"/);
  assert.match(content, /report\("agent-finished"/);
  assert.match(content, /spawn\("watcher", \["event", "--quiet", "pi", event\]/);
  assert.match(content, /payloadWithSurface/);
  assert.match(content, /\.join\("\\n"\)/);
  assert.equal(content.includes('replace(/\\s+/g, " ")'), true);
});

test('installer requires explicit agents and validates before mutating config', async () => {
  const home = await tempHome();
  assert.deepEqual(await runIntegrationsInstall([], { home }), { code: 2, output: 'Usage: watcher integrations install <agents...>\n' });
  assert.deepEqual(await runIntegrationsInstall(['banana'], { home }), { code: 2, output: 'Unknown agent integration(s): banana\n' });
  assert.deepEqual(await runIntegrationsInstall(['pi', 'opencode'], { home }), { code: 2, output: 'Installer not implemented for: opencode\n' });
  await assert.rejects(() => fs.stat(piExtensionPath(home)), /ENOENT/);
});

test('installer dedupes duplicate integration names', async () => {
  const home = await tempHome();
  const result = await runIntegrationsInstall(['pi', 'pi'], { home });
  assert.equal(result.code, 0);
  assert.match(await fs.readFile(piExtensionPath(home), 'utf8'), /watcher integrations install pi/);
});

test('installer overwrites Watcher-managed current or legacy files and refuses conflicts', async () => {
  const home = await tempHome();
  const target = piExtensionPath(home);
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, `// ${WATCHER_MARKER}\nold`, 'utf8');
  await installPiIntegration({ home });
  assert.match(await fs.readFile(target, 'utf8'), /Generated by watcher integrations install pi/);

  await fs.writeFile(target, '// WATCHER_STATUS_HOOK_MANAGED\nold legacy hook', 'utf8');
  assert.equal((await getPiIntegrationStatus({ home })).state, 'outdated');
  await installPiIntegration({ home });
  assert.equal((await getPiIntegrationStatus({ home })).state, 'installed');

  await fs.writeFile(target, '// user extension, hands off', 'utf8');
  await assert.rejects(() => installPiIntegration({ home }), /Refusing to overwrite non-Watcher/);
});

test('watcher integrations status reports missing installed conflict states and compact capabilities', async () => {
  const home = await tempHome();
  assert.equal((await getPiIntegrationStatus({ home })).state, 'missing');
  assert.match(await runIntegrationsStatus({ home }), /pi: missing.*event ingestion supported.*deltas not-implemented/);
  assert.match(await runIntegrationsStatus({ home }), /opencode: installer not implemented.*event ingestion supported/);
  await installPiIntegration({ home });
  assert.equal((await getPiIntegrationStatus({ home })).state, 'installed');
  assert.match(await runIntegrationsStatus({ home }), /pi: installed/);
  await fs.writeFile(piExtensionPath(home), '// unmanaged', 'utf8');
  assert.equal((await getPiIntegrationStatus({ home })).state, 'conflict');
  assert.match(await runIntegrationsStatus({ home }), /pi: conflict/);
});

test('generated Pi extension is command-boundary only', () => {
  const content = generatePiExtension();
  assert.match(content, /watcher", \["event", "--quiet", "pi", event\]/);
  assert.doesNotMatch(content, /net\.createConnection/);
  assert.match(content, /child\.stdin\.end\(JSON\.stringify\(payloadWithSurface\(payload\)\)\)/);
});
