import { test } from 'bun:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { generatePiExtension, getPiHookStatus, installPiHook, piExtensionPath, runHooksInstall, runHooksStatus, WATCHER_MARKER } from '../src/hooksInstaller.js';

async function tempHome(): Promise<string> {
  return fs.mkdtemp(path.join(os.tmpdir(), 'watcher-hooks-'));
}

test('watcher hooks install pi writes managed Pi extension and reload guidance', async () => {
  const home = await tempHome();
  const result = await runHooksInstall(['pi'], { home });
  const target = piExtensionPath(home);
  const content = await fs.readFile(target, 'utf8');
  assert.equal(result.code, 0);
  assert.match(result.output, /Installed Pi Status Hook/);
  assert.match(result.output, /\/reload/);
  assert.match(content, new RegExp(WATCHER_MARKER));
  assert.match(content, /pi\.on\("session_start"/);
  assert.match(content, /report\("session-start"/);
  assert.match(content, /pi\.on\("before_agent_start"/);
  assert.match(content, /report\("prompt-submit", \{ prompt: event\.prompt/);
  assert.match(content, /pi\.on\("message_end"/);
  assert.match(content, /report\("assistant-message"/);
  assert.match(content, /pi\.on\("agent_end"/);
  assert.match(content, /report\("stop"/);
  assert.match(content, /spawn\("watcher", \["hook", "pi", event\]/);
  assert.match(content, /\.join\("\\n"\)/);
});

test('installer overwrites only Watcher-managed files and refuses conflicts', async () => {
  const home = await tempHome();
  const target = piExtensionPath(home);
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, `// ${WATCHER_MARKER}\nold`, 'utf8');
  await installPiHook({ home });
  assert.match(await fs.readFile(target, 'utf8'), /Generated by watcher hooks install pi/);

  await fs.writeFile(target, '// user extension, hands off', 'utf8');
  await assert.rejects(() => installPiHook({ home }), /Refusing to overwrite non-Watcher/);
});

test('watcher hooks status reports missing installed conflict states', async () => {
  const home = await tempHome();
  assert.equal((await getPiHookStatus({ home })).state, 'missing');
  assert.match(await runHooksStatus({ home }), /pi: missing/);
  await installPiHook({ home });
  assert.equal((await getPiHookStatus({ home })).state, 'installed');
  assert.match(await runHooksStatus({ home }), /pi: installed/);
  await fs.writeFile(piExtensionPath(home), '// unmanaged', 'utf8');
  assert.equal((await getPiHookStatus({ home })).state, 'conflict');
  assert.match(await runHooksStatus({ home }), /pi: conflict/);
});

test('generated Pi extension is command-boundary only', () => {
  const content = generatePiExtension();
  assert.match(content, /watcher", \["hook", "pi", event\]/);
  assert.doesNotMatch(content, /net\.createConnection/);
  assert.match(content, /child\.stdin\.end\(JSON\.stringify\(payload\)\)/);
});
