import fs from 'node:fs/promises';
import path from 'node:path';

export const WATCHER_MARKER = 'WATCHER_STATUS_HOOK_MANAGED';
export const PI_EXTENSION_RELATIVE = path.join('.pi', 'agent', 'extensions', 'watcher-status.ts');

export type HookState = 'installed' | 'missing' | 'conflict';

export interface HookInstallOptions {
  home?: string;
}

export interface HookStatus {
  agent: 'pi';
  state: HookState;
  path: string;
}

export function piExtensionPath(home = process.env.HOME || ''): string {
  return path.join(home, PI_EXTENSION_RELATIVE);
}

export function generatePiExtension(): string {
  return `// ${WATCHER_MARKER}
// Generated by watcher hooks install pi. Safe to overwrite by Watcher.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { spawn } from "node:child_process";

function textFromContent(content: unknown): string | undefined {
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {
    const text = content
      .map((part) => part && typeof part === "object" && "text" in part ? String((part as { text?: unknown }).text ?? "") : "")
      .filter(Boolean)
      .join("\\n");
    return text || undefined;
  }
  return undefined;
}

function assistantMessageText(message: unknown): string | undefined {
  const candidate = message as { role?: unknown; content?: unknown } | undefined;
  if (candidate?.role !== "assistant") return undefined;
  return textFromContent(candidate.content);
}

function lastAssistantMessage(messages: unknown): string | undefined {
  if (!Array.isArray(messages)) return undefined;
  for (let index = messages.length - 1; index >= 0; index -= 1) {
    const text = assistantMessageText(messages[index]);
    if (text) return text;
  }
  return undefined;
}

function report(event: string, payload: Record<string, unknown> = {}) {
  try {
    const child = spawn("watcher", ["hook", "pi", event], {
      stdio: ["pipe", "ignore", "ignore"],
      detached: true,
      env: process.env,
    });
    child.stdin.end(JSON.stringify(payload));
    child.unref();
  } catch {
    // Watcher hooks must never break Pi. If this fails, shrug in lowercase.
  }
}

export default function watcherStatusHook(pi: ExtensionAPI) {
  pi.on("session_start", async (event, ctx) => {
    report("session-start", { reason: event.reason, cwd: ctx.cwd });
  });

  pi.on("before_agent_start", async (event, ctx) => {
    report("prompt-submit", { prompt: event.prompt, cwd: ctx.cwd });
  });

  pi.on("message_end", async (event, ctx) => {
    const lastAssistantMessage = assistantMessageText(event.message);
    if (lastAssistantMessage) report("assistant-message", { lastAssistantMessage, cwd: ctx.cwd });
  });

  pi.on("agent_end", async (event, ctx) => {
    report("stop", { lastAssistantMessage: lastAssistantMessage(event.messages), cwd: ctx.cwd });
  });
}
`;
}

export async function getPiHookStatus(options: HookInstallOptions = {}): Promise<HookStatus> {
  const target = piExtensionPath(options.home);
  try {
    const current = await fs.readFile(target, 'utf8');
    return { agent: 'pi', state: current.includes(WATCHER_MARKER) ? 'installed' : 'conflict', path: target };
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return { agent: 'pi', state: 'missing', path: target };
    throw error;
  }
}

export async function installPiHook(options: HookInstallOptions = {}): Promise<HookStatus> {
  const status = await getPiHookStatus(options);
  if (status.state === 'conflict') {
    throw new Error(`Refusing to overwrite non-Watcher Pi extension at ${status.path}`);
  }
  await fs.mkdir(path.dirname(status.path), { recursive: true });
  await fs.writeFile(status.path, generatePiExtension(), 'utf8');
  return { ...status, state: 'installed' };
}

export async function runHooksInstall(agents: string[], options: HookInstallOptions = {}): Promise<{ code: number; output: string }> {
  const requested = agents.length > 0 ? agents : ['pi'];
  const unsupported = requested.filter((agent) => agent !== 'pi');
  if (unsupported.length > 0) return { code: 2, output: `Unsupported hook agent(s): ${unsupported.join(', ')}\n` };
  const status = await installPiHook(options);
  return {
    code: 0,
    output: `Installed Pi Status Hook: ${status.path}\nRun /reload in existing Pi panes or restart them for Watcher status reporting.\n`,
  };
}

export async function runHooksStatus(options: HookInstallOptions = {}): Promise<string> {
  const status = await getPiHookStatus(options);
  return `pi: ${status.state} (${status.path})\n`;
}
