import fs from 'node:fs/promises';
import path from 'node:path';
import type { AgentType } from './model.js';
import { AGENT_INTEGRATIONS, getAgentIntegration, isAgentType } from './agents/registry.js';
import type { AgentIntegration } from './agents/types.js';

export const WATCHER_MARKER = 'WATCHER_AGENT_EVENT_SOURCE_MANAGED';
const LEGACY_WATCHER_MARKER = 'WATCHER_STATUS_HOOK_MANAGED';
export const PI_EXTENSION_RELATIVE = path.join('.pi', 'agent', 'extensions', 'watcher-status.ts');

export type IntegrationState = 'installed' | 'outdated' | 'missing' | 'conflict' | 'not-implemented';

export interface IntegrationInstallOptions {
  home?: string;
}

export interface IntegrationStatus {
  agent: AgentType;
  state: IntegrationState;
  path?: string;
}

export function piExtensionPath(home = process.env.HOME || ''): string {
  return path.join(home, PI_EXTENSION_RELATIVE);
}

export function generatePiExtension(): string {
  return `// ${WATCHER_MARKER}
// Generated by watcher integrations install pi. Safe to overwrite by Watcher.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { spawn } from "node:child_process";

function textFromContent(content: unknown): string | undefined {
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {
    const text = content
      .map((part) => part && typeof part === "object" && "text" in part ? String((part as { text?: unknown }).text ?? "") : "")
      .filter(Boolean)
      .join("\\n");
    return text || undefined;
  }
  return undefined;
}

function assistantMessageText(message: unknown): string | undefined {
  const candidate = message as { role?: unknown; content?: unknown } | undefined;
  if (candidate?.role !== "assistant") return undefined;
  return textFromContent(candidate.content);
}

function lastAssistantMessage(messages: unknown): string | undefined {
  if (!Array.isArray(messages)) return undefined;
  for (let index = messages.length - 1; index >= 0; index -= 1) {
    const text = assistantMessageText(messages[index]);
    if (text) return text;
  }
  return undefined;
}

function compactUnknown(value: unknown): string | undefined {
  if (value === undefined || value === null) return undefined;
  let text: string;
  try {
    text = typeof value === "string" ? value : JSON.stringify(value);
  } catch {
    text = String(value);
  }
  return text.replace(/\\s+/g, " ").trim().slice(0, 16000) || undefined;
}

function payloadWithSurface(payload: Record<string, unknown>): Record<string, unknown> {
  const tmuxPane = process.env.TMUX_PANE;
  const surface = tmuxPane ? { backend: "tmux" as const, id: tmuxPane } : undefined;
  return surface ? { surface, ...payload } : payload;
}

function report(event: string, payload: Record<string, unknown> = {}) {
  try {
    const child = spawn("watcher", ["event", "--quiet", "pi", event], {
      stdio: ["pipe", "ignore", "ignore"],
      detached: true,
      env: process.env,
    });
    child.stdin.end(JSON.stringify(payloadWithSurface(payload)));
    child.unref();
  } catch {
    // Watcher integrations must never break Pi. If this fails, shrug in lowercase.
  }
}

export default function watcherAgentEventSource(pi: ExtensionAPI) {
  pi.on("session_start", async (event, ctx) => {
    report("session-started", { reason: event.reason, cwd: ctx.cwd });
  });

  pi.on("before_agent_start", async (event, ctx) => {
    report("user-message", { text: event.prompt, cwd: ctx.cwd });
  });

  pi.on("agent_start", async (_event, ctx) => {
    report("agent-started", { cwd: ctx.cwd });
  });

  pi.on("message_end", async (event, ctx) => {
    const text = assistantMessageText(event.message);
    if (text) report("assistant-message", { text, cwd: ctx.cwd });
  });

  pi.on("tool_execution_start", async (event, ctx) => {
    report("tool-started", { id: event.toolCallId, name: event.toolName, input: compactUnknown(event.args), cwd: ctx.cwd });
  });

  pi.on("tool_execution_update", async (event, ctx) => {
    report("tool-updated", { id: event.toolCallId, name: event.toolName, text: compactUnknown(event.partialResult), cwd: ctx.cwd });
  });

  pi.on("tool_execution_end", async (event, ctx) => {
    report("tool-finished", { id: event.toolCallId, name: event.toolName, output: compactUnknown(event.result), error: Boolean(event.isError), cwd: ctx.cwd });
  });

  pi.on("agent_end", async (event, ctx) => {
    report("agent-finished", { finalMessage: lastAssistantMessage(event.messages), cwd: ctx.cwd });
  });
}
`;
}

function piIntegrationState(content: string): IntegrationState {
  if (content.includes(WATCHER_MARKER)) return 'installed';
  if (content.includes(LEGACY_WATCHER_MARKER)) return 'outdated';
  return 'conflict';
}

export async function getPiIntegrationStatus(options: IntegrationInstallOptions = {}): Promise<IntegrationStatus> {
  const target = piExtensionPath(options.home);
  try {
    const current = await fs.readFile(target, 'utf8');
    return { agent: 'pi', state: piIntegrationState(current), path: target };
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return { agent: 'pi', state: 'missing', path: target };
    throw error;
  }
}

export async function installPiIntegration(options: IntegrationInstallOptions = {}): Promise<IntegrationStatus> {
  const status = await getPiIntegrationStatus(options);
  if (status.state === 'conflict') {
    throw new Error(`Refusing to overwrite non-Watcher Pi extension at ${status.path}`);
  }
  if (!status.path) throw new Error('Pi extension path unavailable');
  await fs.mkdir(path.dirname(status.path), { recursive: true });
  await fs.writeFile(status.path, generatePiExtension(), 'utf8');
  return { ...status, state: 'installed' };
}

function capabilitySummary(integration: AgentIntegration): string {
  const caps = integration.capabilities;
  return `event ingestion ${caps.eventIngestion}, install ${caps.eventSourceInstall}, activity ${caps.activityEvents}, deltas ${caps.assistantDeltas}`;
}

function dedupeAgents(agents: string[]): string[] {
  return [...new Set(agents)];
}

export async function runIntegrationsInstall(agents: string[], options: IntegrationInstallOptions = {}): Promise<{ code: number; output: string }> {
  const requested = dedupeAgents(agents);
  if (requested.length === 0) return { code: 2, output: 'Usage: watcher integrations install <agents...>\n' };
  const unknown = requested.filter((agent) => !isAgentType(agent));
  if (unknown.length > 0) return { code: 2, output: `Unknown agent integration(s): ${unknown.join(', ')}\n` };

  const notInstallable = requested
    .map((agent) => getAgentIntegration(agent as AgentType))
    .filter((integration) => integration.capabilities.eventSourceInstall !== 'supported')
    .map((integration) => integration.type);
  if (notInstallable.length > 0) return { code: 2, output: `Installer not implemented for: ${notInstallable.join(', ')}\n` };

  const lines: string[] = [];
  for (const agent of requested as AgentType[]) {
    if (agent === 'pi') {
      const status = await installPiIntegration(options);
      lines.push(`Installed Pi Agent Event Source at ${status.path}`);
      lines.push('Run /reload in existing Pi panes or restart Pi for the integration to load.');
    }
  }
  return { code: 0, output: `${lines.join('\n')}\n` };
}

export async function runIntegrationsStatus(options: IntegrationInstallOptions = {}): Promise<string> {
  const lines: string[] = [];
  for (const integration of AGENT_INTEGRATIONS) {
    if (integration.type === 'pi') {
      const status = await getPiIntegrationStatus(options);
      lines.push(`pi: ${status.state}${status.path ? ` at ${status.path}` : ''} — ${capabilitySummary(integration)}`);
      continue;
    }
    lines.push(`${integration.type}: installer not implemented — ${capabilitySummary(integration)}`);
  }
  return `${lines.join('\n')}\n`;
}
